apiVersion: apps/v1
kind: Deployment
metadata:
  name: ajktown-fe
  namespace: ajktown
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ajktown-fe
  template:
    metadata:
      labels:
        app: ajktown-fe
    spec:
      containers:
      - name: ajktown-fe
        image: ajktown/wordnote:latest
        env:
        - name: NEXT_PUBLIC_API_URL
          value: http://ajktown-api-svc
        ports:
        - containerPort: 3000
