name: Documentation
description: Improve documentation for the project
labels:
  - documentation
body:
  - type: textarea
    id: documentation
    attributes:
      label: What would you like to be documented?
      description: |
        Please provide as much info as possible
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
    validations:
      required: true

  - type: textarea
    id: todos
    attributes:
      label: TODOs
      value: |
        ```
        - [ ] TODO: Write your TODOs here
        ```