name: Enhancement Tracking Issue
description: Provide supporting details for a feature in development
labels:
  - enhancement
body:
  - type: textarea
    id: feature
    attributes:
      label: What would you like to be added?
      description: |
        Please provide as much info as possible
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
    validations:
      required: true

  - type: textarea
    id: todos
    attributes:
      label: TODOs
      value: |
        ```
        - [ ] TODO: Write your TODOs here
        ```