name: Infrastructure
description: Improve CI/CD for the project
labels:
  - infra
body:
  - type: textarea
    id: infrastructure
    attributes:
      label: What would you like to be added for CI/CD?
      description: |
        Please provide as much info as possible
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
    validations:
      required: true

  - type: textarea
    id: todos
    attributes:
      label: TODOs
      value: |
        ```
        - [ ] TODO: Write your TODOs here
        ```