name: Refactor
description: Refactor codes/structure for the project
labels:
  - refactor
body:
  - type: textarea
    id: refactor
    attributes:
      label: What would you like to be refactored?
      description: |
        Please provide as much info as possible
    validations:
      required: true

  - type: textarea
    id: todos
    attributes:
      label: TODOs
      value: |
        ```
        - [ ] TODO: Write your TODOs here
        ```